"""Split the supporting tables into an internet appendix.

journal expects the manuscript to carry the tables that make the argument and everything
else to sit in an internet appendix. Ten tables stay: the descriptive split, the
headline estimate, the within-pool fixed-effect ladder, the sensitivity analysis, the
size gradient, the policy-shock split, the disposition of vested options, the audited
nonbank balances and the incidence result. Thirteen move, together with the
balance-sheet appendix.

Cross-references are rewritten to literal "Table IA.n", because the main document and
the appendix are compiled separately and a \\ref across documents would need the
appendix's .aux to exist first. The script knows the appendix ordering, so it can
substitute exactly, and it asserts that every moved label was substituted and that no
reference to a moved table survives as a \\ref.
"""
import os, re
from config import PAPER as PAP

MAIN = ["t1", "t4", "p1", "p11", "p10", "t7", "p8", "p4", "p6", "issuers"]

p = os.path.join(PAP, "jmp.tex")
t = open(p, encoding="utf-8").read()

pre, _, rest = t.partition(r"\section*{Tables}")
assert rest, "no Tables section"
envs = re.findall(r"\\begin\{table\}.*?\\end\{table\}", rest, re.S)
by = {}
for e in envs:
    m = re.search(r"\\label\{tab:([a-z0-9]+)\}", e)
    by[m.group(1)] = e
print(f"{len(envs)} tables found: {' '.join(by)}")
missing = [k for k in MAIN if k not in by]
assert not missing, f"MAIN names not present: {missing}"

# keep the main document's order, filtered
order = [re.search(r"\\label\{tab:([a-z0-9]+)\}", e).group(1) for e in envs]
keep = [k for k in order if k in MAIN]
move = [k for k in order if k not in MAIN]
print(f"\nstaying in the manuscript ({len(keep)}): {' '.join(keep)}")
print(f"moving to the appendix ({len(move)}): {' '.join(move)}")

# ---------------------------------------------------------------- appendix A prose
APP_START = r"\section{The balance-sheet evidence: detail}"
appA = ""
if APP_START in t:
    i = t.index(r"\clearpage" + "\n" + r"\appendix")
    j = t.index("%=====================================================================\n"
                r"\section*{Declarations}")
    appA = t[i:j]
    t = t[:i] + t[j:]
    pre, _, rest = t.partition(r"\section*{Tables}")
    print(f"  moved Appendix A prose: {appA.count(chr(10))} lines")

# ---------------------------------------------------------------- strip moved tables
new_rest = rest
for k in move:
    new_rest = new_rest.replace(by[k], "")
new_rest = re.sub(r"\n{3,}", "\n\n", new_rest)
t = pre + r"\section*{Tables}" + new_rest

# ---------------------------------------------------------------- rewrite references
ia_num = {k: i + 1 for i, k in enumerate(move)}
subs = 0
for k, n in ia_num.items():
    for pat in (rf"Table~\\ref{{tab:{k}}}", rf"Table~\\ref{{tab:{k}}}"):
        pass
    a = "Table~\\ref{tab:%s}" % k
    b = "Internet Appendix Table~IA.%d" % n
    subs += t.count(a)
    t = t.replace(a, b)
    a2 = "Tables~\\ref{tab:%s}" % k
    subs += t.count(a2)
    t = t.replace(a2, "Internet Appendix Tables~IA.%d" % n)
    a3 = "\\ref{tab:%s}" % k                       # any bare survivors
    subs += t.count(a3)
    t = t.replace(a3, "IA.%d" % n)
print(f"\nrewrote {subs} cross-references to the appendix")
for k in move:
    assert ("tab:%s" % k) not in t, f"a reference to {k} survived in the manuscript"

open(p, "w", encoding="utf-8").write(t)

# ---------------------------------------------------------------- build the appendix
preamble = t[:t.index(r"\begin{document}")]
preamble = preamble.replace(
    "%  Job market paper -- Arka Prava Bandyopadhyay",
    "%  Internet Appendix -- generated by code/124_internet_appendix.py")

IA = preamble + r"""\renewcommand{\thetable}{IA.\arabic{table}}
\renewcommand{\thefigure}{IA.\arabic{figure}}
\renewcommand{\thesection}{IA.\arabic{section}}

\begin{document}

\thispagestyle{empty}
\begin{center}
\setstretch{1}
{\LARGE\bfseries Internet Appendix}\\[0.6em]
{\large\bfseries Who Can Afford to Exercise?}\\[0.4em]
{\large Non-Transferable Options and the Immobilisation of Distressed Mortgages}\\[1.4em]
{\normalsize Not for publication}
\end{center}

\vspace{1em}
\noindent This appendix collects the supporting tables referenced in the manuscript and
the detail behind the balance-sheet evidence of Section~7.6. Table numbers here are
prefixed IA and are cited in the manuscript by that number. Every figure in this
appendix is generated by the same code as the manuscript's, and every number is the same
macro, so the two cannot drift apart.

\clearpage
""" + appA.replace(r"\clearpage" + "\n" + r"\appendix", "").replace(
        r"\renewcommand{\thesection}{\Alph{section}}", "").replace(
        r"\setcounter{section}{0}", "").replace(
        r"\label{app:balance}", r"\label{app:balance}") + r"""

\clearpage
%=====================================================================
\section*{Supporting tables}
%=====================================================================

""" + "\n\n".join(by[k] for k in move) + r"""

\end{document}
"""
ia_path = os.path.join(PAP, "internet_appendix.tex")
open(ia_path, "w", encoding="utf-8").write(IA)
print(f"wrote {ia_path}")
print("\nappendix table numbering:")
for k, n in ia_num.items():
    cap = re.search(r"\\caption\{(.{0,58})", by[k])
    print(f"   IA.{n:<3} {cap.group(1) if cap else k}")
