"""Cross-reference files for the split builds.

main.tex binds the Internet Appendix into one PDF. paper_only.tex compiles the main paper alone and
ia_standalone.tex compiles the Internet Appendix alone; each needs the other's label numbers. This
script reads the .aux files written by pdflatex and writes label files that the drivers input:

  main.aux       -> tables/ia_labels.tex    (labels defined in the Internet Appendix, for paper_only.tex)
  paper_only.aux -> tables/main_labels.tex  (labels defined in the main paper, for ia_standalone.tex)

Run it after compiling main.tex and paper_only.tex; hyperlink anchors are dropped so that the
references print as plain numbers in the split PDFs. Both output files are bundled, so an Overleaf
project compiles without running this script; rerun it only after adding or renumbering labels."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
PAT = re.compile(r"\\newlabel\{([^}]*)\}\{\{([^}]*)\}\{([^}]*)\}(?:\{([^}]*)\})?(?:\{([^}]*)\})?(?:\{([^}]*)\})?\}")

def labels(aux):
    out = []
    for line in aux.read_text(encoding="utf-8", errors="ignore").splitlines():
        m = PAT.match(line)
        if m and not m.group(1).endswith("@cref"):
            out.append((m.group(1), m.group(2), m.group(3), m.group(4) or ""))
    return out

def write(path, rows, header):
    with path.open("w", encoding="utf-8") as f:
        f.write(f"% {header}\n% Generated by code/crossrefs.py; do not edit.\n")
        for name, val, page, title in rows:
            f.write(f"\\newlabel{{{name}}}{{{{{val}}}{{{page}}}{{{title}}}{{}}{{}}}}\n")
    print(f"wrote {path.relative_to(ROOT)} ({len(rows)} labels)")

main_aux, po_aux = ROOT / "main.aux", ROOT / "paper_only.aux"
if main_aux.exists():
    ia = [r for r in labels(main_aux) if r[0].startswith("ia:") or "IA" in r[1]]
    write(ROOT / "tables" / "ia_labels.tex", ia, "Internet Appendix labels, from main.aux, for paper_only.tex")
else:
    print("main.aux not found; compile main.tex first", file=sys.stderr)
if po_aux.exists():
    write(ROOT / "tables" / "main_labels.tex", labels(po_aux), "Main-paper labels, from paper_only.aux, for ia_standalone.tex")
else:
    print("paper_only.aux not found; compile paper_only.tex first", file=sys.stderr)
